main:
    mac_name: "树莓小PI001"
    user_name: "lipo"
    user_passwd: "lipo8081"
    remote_web_url: "http://www.lipocmma.cn:16616/log_web"
    log_web_url: "{ remote_web_url }/log"
    status_web_url: "{ remote_web_url }/status"


command_out:
    query_ip: "ifconfig eth0 | grep 'netmask' | awk '{print $2}'"

commands_exec:
  - command_name: "frpc init"
    command: "nohup { frpc_frpc_path } -c { frpc_frpc_ini_path } & >> { frpc_frpc_log_path }"
    command_success_msg: "Init Frpc Success"
    command_fail_msg: "Can't Init Frpc"

  - command_name: "fakes3 init"
    command: "mkdir { fakese_s3_path };nohup fakes3 -r { fakes3_s3_path } -p { fakes3_s3_port } --license { fakes3_akes3_license } &"
    command_success_msg: "Init FakeS3 Success"
    command_fail_msg: "Init FakeS3 Fail"

frpc:
    frpc_path: "/home/pi/projects/frp/frp_0.21.0_linux_arm/frpc"
    frpc_ini_path: "/home/pi/projects/frp/jd_frp/jd_frp.ini"
    frpc_log_path: "/tmp/frpc_logger"

fakes3:
    s3_path: "/tmp/buckets"
    s3_port: 8991
    fakes3_license: "8069351278"
